bf16: true
cutoff_len: 1024
dataset: custom_train
do_train: true
finetuning_type: lora
gradient_accumulation_steps: 4
learning_rate: 0.0002
logging_steps: 10
lora_alpha: 16
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
model_name_or_path: D:/测试
num_train_epochs: 3
output_dir: E:\LLaMA-Factory\output\custom_lora
overwrite_cache: true
per_device_train_batch_size: 2
preprocessing_num_workers: 4
save_steps: 500
stage: sft
template: glm4
warmup_ratio: 0.1
